application: matrufsc2
version: 1
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "1h"

builtins:
- appstats: on

handlers:
- url: /js
  static_dir: frontend/public/js
  http_headers:
    Cache-Control: private
    # Cache-Control: public, max-age=3600
    #Pragma: cache

- url: /css
  static_dir: frontend/public/css
  http_headers:
    Cache-Control: private
    #Cache-Control: public, max-age=3600
    #Pragma: cache

- url: /font
  static_dir: frontend/public/font
  http_headers:
    Cache-Control: private
    #Cache-Control: public, max-age=3600
    #Pragma: cache

- url: /secret/update/
  script: matrufsc2.app
  login: admin

- url: /api/.*
  script: matrufsc2.app

- url: /.*
  static_files: frontend/views/index.html
  upload: frontend/views/index.html
  http_headers:
    Cache-Control: public, max-age=3600
    Pragma: cache
